package CamNecT.CamNecT_Server.global.storage.model;

public enum UploadPurpose {
    COMMUNITY_POST_ATTACHMENT,
    PORTFOLIO_ATTACHMENT,
    ACTIVITY_ATTACHMENT,
    ACTIVITY_THUMBNAIL,
    VERIFICATION_DOCUMENT,
    PROFILE_IMAGE
}
